### ISSUE TITLE
different temporal scale

### ISSUE THREAD

**Issue by cymkG** [m-zaniolo/FIND-drought-generator#1]
Thank you for sharing this interesting tool. I noticed that many of the examples provided are focused on monthly time series. I am wondering if this tool can also be used for generating daily time series?

**Comment by m-zaniolo** [comment]
Thanks for your interest! The idea behind the tool can be applied to daily data as well, but the code would need to be adapted. For instance, you would need to adjust the parameters to reshape the matrix from (Ny, 12) for months to (Ny, 365) for daily data etc. It shouldn’t be too difficult but it would probably requires some debugging on your side. 
Best, 
Marta

**Comment by cymkG** [comment]
Thank you so much. A follow-up question about application for the daily time-series is the data length required, I noticed for monthly time series,  there is recommendation length" Generally, an historical record of at least 30 years is necessary, and 50 years is recommended (
[McKee et al., 1993](https://www.sciencedirect.com/science/article/pii/S1364815223003134#b20), FIND: A Synthetic weather generator to control drought Frequency, Intensity, and Duration
)".

**Comment by cymkG** [comment]
Another question is related to different scenarios mentioned in that paper. In the experiment 1, "For this experiment, we generate 10 synthetic time series for the Big Bend streamflow site (
[Fig. 2](https://www.sciencedirect.com/science/article/pii/S1364815223003134#fig2)
)". I am wondering the difference of these 10 scenarios for the experiment, as I noticed that we can change the parameters related to drought to generate different scenarios.   From my current understanding, the 10 scenarios are generated from same drought parameters, so what is the difference between these 10 synthetic time series?  The background of this question that I am considering using the code to generate time series for wet, medium, and dry conditions by adjusting the drought parameters, but I am unsure about the distinction between the 10 synthetic scenarios.  Thank you again for your time (Maybe I can raise a new issue for this question)

**Comment by m-zaniolo** [comment]
Hello, 
Re: length of the timeseries. The suggested timeseries length of 30 years is recommended for the calculation of the drought index in order to sufficiently capture the climatology of the area when calibrating probability distributions. The suggested length remains the same if you use monthly or daily timestep. 

Re: multiple scenarios. Each of the 10 scenarios generated with the same drought parameters should display very similar drought properties, but their difference is in the timing the droughts happen during the time horizon. This allows to create variability in your scenarios. 

Best,
Marta

**Comment by cymkG** [comment]
Thank you so much for the detailed answer🙂
